package imagewall

// Generated by https://quicktype.io

type ImageWall struct {
	Data              Data   `json:"data"`
	BottomTipsVisible bool   `json:"bottom_tips_visible"`
	BottomTipsText    string `json:"bottom_tips_text"`
	Ok                int64  `json:"ok"`
}

type Data struct {
	SinceID interface{} `json:"since_id"`
	List    []List      `json:"list"`
}

type List struct {
	PID           string `json:"pid"`
	Mid           string `json:"mid"`
	IsPaid        bool   `json:"is_paid"`
	TimelineMonth string `json:"timeline_month"`
	TimelineYear  string `json:"timeline_year"`
	ObjectID      string `json:"object_id"`
}
