package info

// Generated by https://quicktype.io

type UserInfo struct {
	Ok   int64        `json:"ok"`
	Data UserInfoData `json:"data"`
}

type UserInfoData struct {
	User      User      `json:"user"`
	TabList   []TabList `json:"tabList"`
	BlockText string    `json:"blockText"`
}

type TabList struct {
	Name    string `json:"name"`
	TabName string `json:"tabName"`
}

type User struct {
	ID                int64      `json:"id"`
	Idstr             string     `json:"idstr"`
	PCNew             int64      `json:"pc_new"`
	ScreenName        string     `json:"screen_name"`
	ProfileImageURL   string     `json:"profile_image_url"`
	ProfileURL        string     `json:"profile_url"`
	Verified          bool       `json:"verified"`
	VerifiedType      int64      `json:"verified_type"`
	Domain            string     `json:"domain"`
	Weihao            string     `json:"weihao"`
	VerifiedTypeEXT   int64      `json:"verified_type_ext"`
	AvatarLarge       string     `json:"avatar_large"`
	AvatarHD          string     `json:"avatar_hd"`
	FollowMe          bool       `json:"follow_me"`
	Following         bool       `json:"following"`
	Mbrank            int64      `json:"mbrank"`
	Mbtype            int64      `json:"mbtype"`
	PlanetVideo       bool       `json:"planet_video"`
	VerifiedReason    string     `json:"verified_reason"`
	Description       string     `json:"description"`
	Location          string     `json:"location"`
	Gender            string     `json:"gender"`
	FollowersCount    int64      `json:"followers_count"`
	FollowersCountStr string     `json:"followers_count_str"`
	FriendsCount      int64      `json:"friends_count"`
	StatusesCount     int64      `json:"statuses_count"`
	URL               string     `json:"url"`
	CoverImagePhone   string     `json:"cover_image_phone"`
	IconList          []IconList `json:"icon_list"`
	UserType          int64      `json:"user_type"`
	IsStar            string     `json:"is_star"`
	Wenda             string     `json:"wenda"`
	IsMuteuser        bool       `json:"is_muteuser"`
	SpecialFollow     bool       `json:"special_follow"`
}

type IconList struct {
	Type string       `json:"type"`
	Data IconListData `json:"data"`
}

type IconListData struct {
	Mbrank int64 `json:"mbrank"`
	Mbtype int64 `json:"mbtype"`
}
